### ISSUE TITLE
Row values are clipped for Mac version of HPCViewer

### ISSUE THREAD

**Issue by aarontcopal2** [HPCToolkit/hpcviewer.e4#101]
The row values get clipped in profile and trace view of HPCViewer. The viewer version is 2021.05 (Commit: 7867429)
![image](https://user-images.githubusercontent.com/17940384/124971964-6cc59d00-dfef-11eb-961f-1a625821272b.png)

**Comment by laksono** [comment]
This is a related bug on Linux/GTK: if we increase the font size at the profile view, the row's height is not adjusted accordingly.
However, if we reload the database, everything looks fine. Apparently refreshing the table doesn't work properly on Linux/GTK?

![image](https://user-images.githubusercontent.com/8781032/134386815-ad10c5a7-3ca0-49a9-87dc-c029713aaee8.png)

**Comment by laksono** [comment]
This issue can be fixed easily using NatTable widget which is for the next release (2021.12).
It's just too tricky to fix using SWT table.
