### ISSUE TITLE
Vanishing metric data when changing sorting in top-down view (Linux)

### ISSUE THREAD

**Issue by blue42u** [HPCToolkit/hpcviewer.e4#11]
When changing the sorting column in the top-down view, if an entry other than the first "Aggregate Metrics" line is selected all lines become blank and don't come back after switching tabs.

**EDIT:** The appears to only occur whenever there is only one root node, databases with threads or partial call paths (etc.) are unaffected. (Also removed the effects reported in #12)

Seen on Linux with OpenJDK (11 and 13).

To reproduce:
1. Pull up a database with one root node (`hpcrun -e REALTIME@100 ls` suffices, e.g. [bug-confusing-collapse.zip](https://github.com/HPCToolkit/hpcviewer.e4/files/5126833/bug-confusing-collapse.zip)), and open some contexts:
![image](https://user-images.githubusercontent.com/17242663/90441008-d5392200-e09d-11ea-8d0f-7a0a3789251f.png)
2. Select one of them, then click a column header. Note that no metric data is rendered:
![image](https://user-images.githubusercontent.com/17242663/90441181-20533500-e09e-11ea-9ec4-4a304a9643ae.png)
3. Switch tabs (to e.g. bottom-up and back), note that data does not reappear.

**Comment by laksono** [comment]
Is it in master or develop branch?
Sanity check: Is it the latest version of hpcviewer.e4?

**Comment by laksono** [comment]
I check the master branch on llnl.cs, I didn't have the same problem.

**Comment by blue42u** [comment]
I was running a just-pulled `master`, I can reproduce on `develop` as well. This is on my home machine, haven't tried any of the Rice machines yet.

Also, it looks like I can get the data back by selecting the aggregate line and sorting again. But its a bit of an awkward workaround.

**Comment by laksono** [comment]
I think I need more information to reproduce your problem:
- What distro? Ubuntu? Which version?
- What window manager do you use? Gnome?

**Comment by blue42u** [comment]
- Debian Unstable/Sid. Probably Testing/Bullseye would see it too.
 - GNOME 3.36 (Eclipse seems to use GTK 3.24). Specifically GNOME Shell.

**Comment by blue42u** [comment]
Confirmed
