### ISSUE TITLE
nattable: traces are not properly ordered 

### ISSUE THREAD

**Issue by mxz297** [HPCToolkit/hpcviewer.e4#125]
I built the develop branch of hpcviewer.e4 yesterday (commit ab056ccc4ef9f73ccf9b1c07b54221d775e7697a) and use it to open a databased generated by prof2 branch of the hpctoolkit on a Macbook.

The application is WarpX collected on Perlmutter with 16 ranks and 16 GPUs:

![image](https://user-images.githubusercontent.com/1683713/139100764-823cd81c-6a30-4acc-8349-44a0119f1e75.png)

The traces do not seem to be properly ordered. I saw trace lines from different ranks inter-mangled.

The database can be found on ufront at `/home/xm13/warpx-traces.d.zip`

**Comment by laksono** [comment]
Can you describe more details? Which ranks are inter-mingled?
I looked at the list of ranks, it looks well ordered.

![image](https://user-images.githubusercontent.com/8781032/139109298-6c5fae9b-1246-40a8-a6a6-6510d4fb3fbe.png)

**Comment by mxz297** [comment]
In your screenshot, the order is rank 1,1,1,2,3,0,0,0,0,1,2,2. They are not sorted.

**Comment by laksono** [comment]
Well, that's because they are from different nodes. 
I think what you need is to enable to sort based on rank number and ignore the node number. This is not implemented yet.

**Comment by mxz297** [comment]
> Well, that's because they are from different nodes. I think what you need is to enable to sort based on rank number and ignore the node number. This is not implemented yet.

I see. @blue42u I don't quite know how a rank can appear on multiple nodes. In addition, I only requested 4 nodes but the results seem to show more than 4 different node numbers. Could this be actually a prof2 problem?

**Comment by blue42u** [comment]
@mxz297 Prof2 just uses whatever id-tuple was passed to from Run, so if there is an error in the id-tuples it would be in Run somewhere (either for generating the hostid/rank numbers or stashing those in the id-tuples).

The other possibility is that the measurements dir wasn't cleaned between runs, that would also cause this effect.

**Comment by mxz297** [comment]
@laksono @blue42u I can confirm that this is not a viewer problem: I re-run the application with prof2 branch and the master branch. The database generated with the prof2 branch has trace lines unsorted but the database generated by the master branch has things in order.
