### ISSUE TITLE
%-sign hidden when rendering metric values close to 100%.

### ISSUE THREAD

**Issue by blue42u** [HPCToolkit/hpcviewer.e4#13]
When viewing databases with metric values close to (but not exactly) 100% of the aggregate, the percentage is rendered one space after the column edge (and thus hidden).

To reproduce:
1. Open up a database of such an application ([bug-hidden-percent.c](https://github.com/HPCToolkit/hpcviewer.e4/files/5086954/bug-hidden-percent.txt) seems to work, database 
[bug-hidden-percent.zip](https://github.com/HPCToolkit/hpcviewer.e4/files/5086955/bug-hidden-percent.zip)). Note the missing `%` in applicable cases:
![image](https://user-images.githubusercontent.com/17242663/90447817-b3459c80-e0a9-11ea-9656-eaf23381c9cc.png)
2. Go to other tabs, see the same effect:
![image](https://user-images.githubusercontent.com/17242663/90447840-c5bfd600-e0a9-11ea-83b0-929757c568bb.png)
![image](https://user-images.githubusercontent.com/17242663/90447848-cb1d2080-e0a9-11ea-8b3b-c714604d0540.png)

Reported by @jmellorcrummey

**Comment by laksono** [comment]
This is an excellent example. Thanks for the database

**Comment by laksono** [comment]
The content of the table (with the real value):
```
"Experiment Aggregate Metrics"  2.003944
...
"clock_nanosleep.c: 80"  2.00364
```
The cost of `clock_nanosleep.c: 80` is `2.00364`, which is `99.98%` of the total execution time. Java's formatter rounds it correctly to `100.0%,`. This is correct since 99.98 is closer to 100.0 than to 99.9.

**Comment by jmellorcrummey** [comment]
we can just allocate space for another digit.

**Comment by laksono** [comment]
That solves this special case, but I am afraid not for general cases.
We cannot keep adding digits to avoid rounding to 100.0%.

**Comment by blue42u** [comment]
If I'm thinking right, there are only three cases to consider for percentages:
 - `>`99.9444...%, where it should round to `100.%`
 - `>`9.9444...%, where we can use the usual format string: `12.3%`
 - All other cases, where we can have one extra decimal after the point: `2.34%`, `0.45%`, etc.

Its awkward, but can we write this sort of logic somewhere once and handle it that way?

Alternatively, if we're ok with bad rounding in the last place, we can just truncate it to fit in 4 characters.

**Comment by laksono** [comment]
I made mistake, it turns out we wrote our own format instead of using Java's [DecimalFormat](https://docs.oracle.com/javase/8/docs/api/java/text/DecimalFormat.html) class (note: hpcviewer's plot graph uses this class to display ticks on y-axis). 
I'll check if it's possible to rewrite the format using a customized DecimalFormat.
