### ISSUE TITLE
Extra blank leaf level in trace view

### ISSUE THREAD

**Issue by blue42u** [HPCToolkit/hpcviewer.e4#14]
The trace view lists an extra blank context one "deeper" than the application, messing up the rendering in the depth view.

Seen on Linux (OpenJDK 13), master + develop branches.

To reproduce:
1. Open a database with traces (`hpcrun -e REALTIME@100 -t ls`, 
[bug-extra-depth.zip](https://github.com/HPCToolkit/hpcviewer.e4/files/5087048/bug-extra-depth.zip)), and open the trace view. Note the depth of the deepest application context, and the active `+` button on the depth field.
![image](https://user-images.githubusercontent.com/17242663/90449210-952d6b80-e0ac-11ea-8553-2ef902a719f6.png)
2. Go down as far as possible (via `+` or the max-depth button). Note the extra blank context, and the suspicious depth view rendering.
![image](https://user-images.githubusercontent.com/17242663/90449298-c017bf80-e0ac-11ea-9eae-2f4578ad6465.png)

**Comment by laksono** [comment]
Fixed in commit 9ffee3e1be145524a2eeb95286ec25976a8e8c0d in develop branch.

**Comment by blue42u** [comment]
Confirmed.
