### ISSUE TITLE
Trace rulers could use enhancement

### ISSUE THREAD

**Issue by blue42u** [HPCToolkit/hpcviewer.e4#20]
Was hunting down the performance problems in Prof2 over the weekend, and ran into a few annoyances with the trace viewer.

These are purely my opinions, suggestions are welcome. Of course none of this should be prioritized over true bugs.

1. Depending on the domain of the time dimension, there are cases where the status header and ruler don't match:
![image](https://user-images.githubusercontent.com/17242663/95007319-0cbf4780-05d4-11eb-8a11-b36927e1c588.png)
Not only do they not match units, the cursor truncates instead of rounds to get its value. It would be more helpful to have a cursor line with at least the granularity of the ruler, and preferably slightly higher (in this example, individual ms).

2. The first few major tick marks are of a different size from the rest, even though the minor ticks are the same:
![bars](https://user-images.githubusercontent.com/17242663/95007436-9d4a5780-05d5-11eb-86ee-5204a25ac264.png)
This is just plain confusing, shifts all the ticks to a weird offset, and otherwise makes it a pain to guesstimate the value of a tick mark.

    There are also a lot of extra zeros when the ticks are multiples of 100, and the next lower granularity is inconsistently placed on minor tick marks. It would be nicer to round up the prefix and use multiples of 5 and 2, for the above example this is `.5s` or `.2s`:
    ```
    0s    0.2s    0.4s    0.6s    0.8s    1s    1.2s    1.4s    1.6s ...
    ```
    This makes it much easier to round by eye, easy to see the coarse marks (especially if `1.0s` is written as `1s`), and keeps the character count down to rational levels.

3. When you zoom in on a sufficiently long execution, the numbers in the ruler can get really large (there are cases much worse than mine out there):
![image](https://user-images.githubusercontent.com/17242663/95007621-39289300-05d7-11eb-93a1-9bc08d8e37d1.png)
When this happens, it would be nicer to remove the common prefix from all the numbers, for e.g. something like:
    ```
    510ns    620ns    700ns    780ns    860ns    940ns    1020ns       1100ns    1180ns
    7.561173s+
    ```
    For maximum readability the offset could be of the form `<hours>:<minutes>:<seconds>.<partial seconds>+` (or `xx.xxxms` or `us` or `ns` when close to the start).

Ping @laksono and @jmellorcrummey at minimum, the rest of the team most likely have opinions worth hearing as well.

**Comment by laksono** [comment]
Wow, good observation. 
You have the points, and this is not difficult to fix, just not a priority at the moment.

**Comment by jmellorcrummey** [comment]
I agree with all of Jonathon's points. Thanks for the careful design review.

**Comment by blue42u** [comment]
@laksono Can this be added to the list of enhancements for the 2022.04 release? All of these issues are still very present on the current `develop`.

**Comment by laksono** [comment]
@blue42u sure, we can always try to fit it to release 2022.04. Thanks for the reminder.
Btw: It isn't fully fixed, that's why it isn't closed yet.

**Comment by jmellorcrummey** [comment]
The issue with rulers persists in the 2022.01 release. 

I can't even imagine why the code would alternate back and forth between two different spacings of 10s and 20s as shown below. First, it increases spacing from 10s to 20s (90->100 then 100->120), decreasing back to 10s (160->170) increasing to 20s again (170->190), and then back to 10s again (190->200), then back to 20s again (200->220). 

<img width="916" alt="image" src="https://user-images.githubusercontent.com/3926112/156031581-0ba6b13f-5eea-48bb-a2dc-8409809c8289.png">

**Comment by laksono** [comment]
This issue is not fully resolved yet. That's why the label is not "resolved".
Concerning the spacing, it still depends on whether there's a space or not. 
We can make it simpler by only showing every 20s instead of every 10s and try to check whether it fits or not.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpcviewer/-/issues/20)
