### ISSUE TITLE
hpcviewer.e4 doesn't wrap long function names in the tool tip

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer.e4#25]
In working with the Oct 24 version 09a572a7216793e0ddd8f8539211811a670295f1, it doesn't wrap long function names in the tool tip. 

![image](https://user-images.githubusercontent.com/3926112/97098946-cb5d0d80-1650-11eb-8a65-b5381ad9b5e5.png)

**Comment by laksono** [comment]
Fixed in 2353887331cd704ffeba799e2416135fab502d1f
