### ISSUE TITLE
File menu actions (on Linux)

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer.e4#38]
I found the File menu actions on Linux to be counter-intuitive. 

- "Open database" apparently means "Switch database". I think that "Open database" should have the semantics of "Add database"
- "Close" only appears when more than one database is loaded. Why can't I close a single open database?
- For consistency, the "Close" action should be named "Close database".

Platform: Linux. Branch: master. Git hash: 8aacb10d0ffcd003da960d469a4378b877c8c8e2

**Comment by laksono** [comment]
True, the "Close" menu item only appears when there are more than one database. That's on purpose. If the user wants to close all databases, he/she just close the viewer (the application).
I agree it should be "Close database". The name was "Close database" but somehow it becomes "Close" after some merges.

**Comment by jmellorcrummey** [comment]
I wanted to use it the way I always have: I wanted to close one database and open another. I was confused that there was no close. I found that after adding the second database I could close the first. Unless there is a reason to not close a singleton database to return to the initial state (nothing open), I think it would be better to have close visible after a single database is open or even always visible.

**Comment by laksono** [comment]
The word "Switch database" makes more sense.
- If there's no database, the menu is "Open database"
- If there is at least one database opened, we should add a menu item "Switch database" to allow users to replace the existing database with another one.

**Comment by laksono** [comment]
Fixed
