### ISSUE TITLE
Tooltip for profile and trace tabs

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer.e4#39]
First, I am glad to have a tooltip for these tabs. However, there is a minor inconsistency. 

The profile tooltip says "<database name>". The trace tooltip says "Traces from <database name>". They should be consistent. Either it should be "Profile from <database name>" for the profile tab, or both tabs should just list the database name for the tooltip. The tab itself tells you whether it is a Profile or a Trace.

**Comment by laksono** [comment]
Good point! I didn't pay attention to details.
We should just display the database **_path_** (the _path_ is guaranteed to be unique, while the _name_ is not).

**Comment by laksono** [comment]
Fixed in develop branch commit e8ee97e
