### ISSUE TITLE
Trace overcounts CPU time when thread sleeps

### ISSUE THREAD

**Issue by martyitz** [HPCToolkit/hpcviewer.e4#46]
The trace shows data between the last recorded CPU Time tick and the next tick,
even though they are separated by a period when the thread is asleep

**Comment by martyitz** [comment]
That period should be shown as white space

**Comment by laksono** [comment]
@martyitz Can you describe more details? Do you have the screenshots?

**Comment by martyitz** [comment]
> On Mar 24, 2022, at 10:31 AM, Laksono Adhianto ***@***.***> wrote:
> @martyitz <https://github.com/martyitz> Can you describe more details? Do you have the screenshots?
> 
>  
It has been 15 months since I filed the incident.

I tried to reproduce the problem today, and it does not appear using the 2022.01 installed bits, nor with the
bits in my build area.  I ran synprog cpu.dousl.icpu   Each of those three tasks takes ~3 seconds
of clock time.  The dousl task uses 0.01 seconds of CPU time; the other two use about 3 seconds of CPU time.
The viewer correctly shows white space for the dousl task in the trace view.

Do you remember fixing this?  I would say this bug is fixed in any case.

	Marty

**Comment by laksono** [comment]
I don't remember fixing this. 
Btw, I'll close it since it's fixed with the latest version
