### ISSUE TITLE
when a profile database opens on Linux, it is missing the glyph that showing sort order

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer.e4#73]
when hpcviewer is first opened on a profile, it lacks the triangle in the title of the first column indicating that it is sorted in decreasing order.

this should not hold up the release.

**Comment by laksono** [comment]
This looks like a GTK problem (or the interaction between SWT and GTK). If the columns fit the panel, it shows the sort indicator. 

![image](https://user-images.githubusercontent.com/8781032/110006392-34c7e980-7cdf-11eb-91c6-b808f4bed669.png)

If the database has a lot of metric columns, the sort indicator disappears.

![image](https://user-images.githubusercontent.com/8781032/110006501-5de87a00-7cdf-11eb-9102-e4f82bad5d8d.png)

This issue doesn't occur on MacOS.

**Comment by laksono** [comment]
Fixed in commit c444e3ad7d59e218255426c00ee4347f8c7e4092
