### ISSUE TITLE
when a CCT filter is added, working state is lost

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer.e4#79]
When a CCT filter is added, the node selection is lost. 

- If the selected node is not filtered, the selected node should be preserved and the path to it should be expanded on the screen
- If the node were filtered, it would be appropriate to place the selection on the first unfiltered parent and the path to it should be expanded on the screen.

When a CCT filter is added, the column selection and sort order is lost. It should be retained.

**Comment by laksono** [comment]
- The metric selection has to be preserved. If metric X is sorted, after the refresh, this metric is also sorted
- Caveat: There's a bug inside Eclipse JFace (at least in older version) that the API to check if a tree node is expanded or not, will trigger an event to retrieve the content of all the children recursively. This causes performance issue for large trees.

**Comment by jmellorcrummey** [comment]
I think the Eclipse JFace bug can be avoided. 

Presently, the whole tree closes up after applying a filter. You know what the selection is. Simply expand the nodes along the path from the selection to the root and restore the selection. No queries are necessary.

**Comment by jmellorcrummey** [comment]
1. perform a recursive traversal from the selection to the root.
2. when the root is reached, expand the ancestors in reserve order
3. don't expand the selection itself
4. once the selection's parent is expanded, restore the selection so that it is visible on the screen

**Comment by laksono** [comment]
Yup. The bottom-up approach looks feasible.

**Comment by laksono** [comment]
Preserving the tree expansion is resolved on Mac. On Linux/GTK is still working on progress.
