### ISSUE TITLE
opening a database with no metrics throws and error and the file button is disabled

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer.e4#80]
<img width="628" alt="image" src="https://user-images.githubusercontent.com/3926112/113807125-2da25a00-9729-11eb-8fd4-80b80c35b75f.png">

**Comment by laksono** [comment]
Can you share the database? It works with me for empty metrics:

![image](https://user-images.githubusercontent.com/8781032/113808339-6e02d780-972b-11eb-8901-ed2c2cc6a4ee.png)

**Comment by jmellorcrummey** [comment]
The link to the database that causes the problem on x86_64 2021.03.01 release:

https://rice.box.com/s/7ovjrlfouk9xbbgdjspv04n8qvprmeed

**Comment by jmellorcrummey** [comment]
actually, the database contains no call path at all. I am working to determine why that is so. however, I think we need to make all of our components as resilient as possible.

**Comment by laksono** [comment]
Got it. I can reproduce it.

**Comment by laksono** [comment]
Resolved in develop branch
