### ISSUE TITLE
minimize hpcviewer window on mac with a keyboard command

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer.e4#85]
It would be nice if <command>m would minimize hpcviewer on a mac, the way it does for other applications.

**Comment by laksono** [comment]
Fixed in def459326ea0b7909a13bdaccc0d687873d90b79 resolved on Mac with Cmd-M shortcut.
On Linux: ctrl+M (not standard)
On Windows: ctrl+M (not standard)
