### ISSUE TITLE
RFE: Line numbers for the trace view

### ISSUE THREAD

**Issue by blue42u** [HPCToolkit/hpcviewer.e4#96]
(Sorry for the delay in getting this as an issue, got sidetracked with the million other things to do. I added/expanded some ideas while I was at it. Ping @laksono @jmellorcrummey)

Currently, the trace view has no way to distinguish between repeated calls to a function on different source lines, which may have vastly different costs and code paths despite following the same function calls. While a Structfile can assist when loops are present, if there are no loops or if the loops are inside function calls Structfiles are ineffective.

Example (simplified) use case: the following code snippet
```c
#include <time.h>
#include <stdio.h>
#include <stdbool.h>
void foo(bool fast_mode) {
  struct timespec ts = {fast_mode ? 1 : 4, 0};
  while(nanosleep(&ts, &ts));
}
int main() {
  foo(true);  // Takes 1 second
  struct timespec ts = {0, 2000000};
  while(nanosleep(&ts, &ts));
  foo(false);  // Takes 4 seconds
  return 0;
}
```
can/will generate a trace such as the following ([fr-line-numbers-for-trace.zip](https://github.com/HPCToolkit/hpcviewer.e4/files/6605384/fr-line-numbers-for-trace.zip)):
![image](https://user-images.githubusercontent.com/17242663/120948740-85991500-c708-11eb-9690-8b3445230a01.png)
While there is a call to `main -> nanosleep` (marked with the cursor), its "swallowed up" by the comparatively more expensive calls to `foo` around it and may not even be sampled if small enough. For cases with more calls to `foo` with different parameters, this is unacceptably difficult to identify which call specifically is the one in need of adjustment.

---

The proposed solution is to add line numbers to the "call stack" pane, both to the left of the procedures and in the tooltip. Mock up:
![fr-line-number-for-trace](https://user-images.githubusercontent.com/17242663/120953815-7a97b200-c713-11eb-8dca-efb92de189bc.png)
The line numbers should match the colors and meanings used in the profile tab, and clicking a line number should jump to that location in the source pane. Clicking the procedure name should change the depth as it does now since the color swatches are too small a target for that role. (@jmellorcrummey suggested the above should be off by default, I don't see a reason to do so since it matches the profile tab's UI, does not remove or muddle functionality and only spends ~10-15 pixels of user-adjustable horizontal space).

To make room for the source pane, the "profile" and "trace" tab row should be moved to the bottom of the interface. Alternatively, the "trace" tab could be placed inline with the "top-down," "bottom-up" and "flat" view tabs. In this case selecting it only changes the bottom half of the interface, and some sort of easy toggle should be added to hide the source pane for full-screen trace viewing.

The statistics pane should not break functions into lines by default, that would create too many entries and muddle the results.
One option is to add a per-function toggle for whether to break it into lines or not, mock up:
![fr-line-number-for-trace-stats](https://user-images.githubusercontent.com/17242663/120956916-44116580-c71a-11eb-8f37-7d2ce90ac3fc.png)
Clicking the icon (drop down menu also an option) switches between function-level (left) and line-level (right) views. Entries with multiple functions (grouped together by **explicit** color mappings) should always be function-level.

Sufficiently large function-bars in the trace view (both horizontally and vertically) should be inset with a secondary "mini-trace" for source lines, mock up:
![fr-line-number-for-trace-minitrace](https://user-images.githubusercontent.com/17242663/120960220-f815ef00-c720-11eb-8bdc-65cad8bc19ec.png)
This inset trace should only be rendered if the function bar is sufficiently large to maintain a border around the inset (e.g. 2-5 pixels horizontal, 10-20 pixels vertical) and have a fixed maximum height (e.g. 22-30 pixels) slightly taller than the cursor. The colors should be contrasting with the same or opposing hue as the function bar (e.g. desaturated and adjusted value). These colors should also be inset into the color swatches in the call stack pane and statistics pane (if line-level view is toggled on).

**Comment by jmellorcrummey** [comment]
@martyitz fyi - proposed trace view changes

**Comment by laksono** [comment]
@martyitz @jmellorcrummey @blue42u 
Another possible layout recommended by one of our users is to split between profile and trace views assuming the display is big enough. However, this layout will be hard to use if the number of metrics is huge. Btw, having a lot of metrics is always problematic.

![image](https://user-images.githubusercontent.com/8781032/121058489-fe8a8200-c785-11eb-8deb-56cc8e289605.png)

**Comment by jmellorcrummey** [comment]
@laksono an advantage to what you propose is that from the trace pane, we could not only show the source for a call site or a procedure, we could also highlight the selection in the navigation pane as well. 

We should discuss this at the group meeting.

**Comment by martyitz** [comment]
I think the notion of being able to navigate from any part of the GUI to any other part is highly desirable.

However, we are embarking on a GUI usability study, and I think it's premature to design a solution before
we have the data from the users.

Screen real-estate is an important constraint that must be considered.  Currently, the top-down pane
is too constrained, especially with more than one or two metrics.  The issue of real-estate is an important
one to raise with the users.  We can't decide how to lay everything out until we know how the users will
want to do the navigation.

**Comment by laksono** [comment]
Suggestions:
- Have a preference to show/hide the loops, line number, etc.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpcviewer/-/issues/96)
